name: PHP Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install composer dependencies (if composer.json present)
        run: |
          if [ -f composer.json ]; then composer install --no-progress --no-suggest --prefer-dist --no-interaction; fi

      - name: Run tests
        run: |
          php tests/run_all.php
        env:
          TZ: UTC
